apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "common.fullname" . }}-cnpg
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  instances: 3
  bootstrap:
    initdb:
      database: keycloack
      owner: sa
      secret:
        name: {{ include "common.fullname" . }}-cnpg-user
  enableSuperuserAccess: true
  superuserSecret:
    name: {{ include "common.fullname" . }}-cnpg-superuser
  storage:
    size: 10Gi
---
{{- $userPassword := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-cnpg-user
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ "myappadmin" | b64enc | quote }}
  password: {{- if not (lookup "v1" "Secret" .Release.Namespace (include "common.fullname" .)) }}
              {{ $userPassword | b64enc | quote }}
            {{- else }}
              {{ .Values.postgresql.userPassword | default $userPassword | b64enc | quote }}
            {{- end }}
---
{{- $superPassword := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-cnpg-superuser
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ "sa" | b64enc | quote }}
  password: {{- if not (lookup "v1" "Secret" .Release.Namespace (include "common.fullname" .)) }}
              {{ $superPassword | b64enc | quote }}
            {{- else }}
              {{ .Values.postgresql.superPassword | default $superPassword | b64enc | quote }}
            {{- end }}
