apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
    {{- include "common.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-keycloak
  type: LoadBalancer